### ISSUE TITLE
Decrypt secret and ignore header

### ISSUE THREAD

**Issue by gregfurman** [sosedoff/ansible-vault-go#5]
The decrypting of an `ansible-vault` a secret using the `vault.Decrypt` function fails when the `$ANSIBLE_VAULT;1.1;AES256` header is present in the secret. In contrast, removing the header allows the secret to be decrypted fine.

Currently I am just skipping the first line of the string but this is unexpected behavior since `ansible-vault` normally handles this.

**Comment by sosedoff** [comment]
Hey @gregfurman, why close the issue?

**Comment by gregfurman** [comment]
@sosedoff There was an error on our side. Your package is working just fine!

**Comment by sosedoff** [comment]
Good to hear!
